### ISSUE TITLE
symbol_template.svg is missing!

### ISSUE THREAD

**Issue by EDR-Hat** [TobseF/Emoji-Font-to-SVG-Extractor#1]
I was attempting to use your script and it looks like it needs a file called 'symbol-template.svg' to run. I could try to write my own svg file but I don't want to guess if you still have it somewhere.

Thanks for writing this!

**Comment by TobseF** [comment]
Oh... thanks for the hint. I missed the file with the initial commit.
Just added it here: https://github.com/TobseF/Emoji-Font-to-SVG-Extractor/commit/aa65251b1f3e94c0a11f5bc3a39bddd41574e092
